import { auth } from "~/server/auth";
import NavBar from "../_components/NavBar";

import { type Metadata } from "next";

// TODO: This will have the username in the title when logged in
export const metadata: Metadata = {
  title: "Munchlax: A friendly food tracker",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function DashboardLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const session = await auth();

  return (
    <main className="flex-column ml-auto mr-auto w-screen max-w-7xl content-center">
      <NavBar user={session?.user} />
      {children}
      <div className="divider mx-auto w-4/5 lg:w-full" />
      <p>Footer goes here</p>
    </main>
  );
}
